version: '3'
services:
  gateway:
    image: dregistry.moovapps.com/visiativ/process/moovapps-zuul-gateway:nightly
    restart: ${RESTART_POLICY}
    ports:
      - '80:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge