version: '3'
services:
  keycloak:
    image: jboss/keycloak:6.0.1
    restart: ${RESTART_POLICY}
    command:
      [
        '-b',
        '0.0.0.0',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
        '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
        '-Djboss.socket.binding.port-offset=1000',
      ]
    volumes:
      - ./keycloak/realm-config:/opt/jboss/keycloak/realm-config
      - ./keycloak/providers:/opt/jboss/keycloak/standalone/deployments
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mariadb
      - DB_ADDR=mariadb
      - DB_PORT=3306
      - DB_DATABASE=keycloak
      - DB_USER=root_keycloak
      - DB_PASSWORD=manager
    ports:
      - 9080:9080
      - 9443:9443
      - 10990:10990
    depends_on:
      - mariadb
      - kafka
    networks:
      - backend

networks:
  backend:
    driver: bridge
