version: '3'
services:
  mariadb:
    image: mariadb:10.4
    restart: ${RESTART_POLICY}
    volumes:
        - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        - ./mariadb/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=manager
    ports:
      - 3306:3306
    networks:
      - backend

networks:
  backend:
    driver: bridge
    