version: '3'
services:
  mongodb:
    image: mongo:4.0
    restart: ${RESTART_POLICY}
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb/data:/data/db/
    networks:
      - backend

networks:
  backend:
    driver: bridge