version: '3'
services:
  ouroboros:
    image: pyouroboros/ouroboros
    restart: ${RESTART_POLICY}
    environment:
      - CLEANUP=true
      - INTERVAL=60
      - LOG_LEVEL=info
      - SELF_UPDATE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock