version: '3'
services:
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=60
      - LOG_LEVEL=info
      - SELF_UPDATE=true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock